services:
  db:
    image: postgres:17.9
    restart: always
    volumes:
      - ./database/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=mydb-tutorial-yt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
